Vagrant.configure("2") do |config|
	
	nfs_status = (ENV['WINDOWS']) ? false : true
	
	config.vbguest.iso_path = "../veewee/iso/VBoxGuestAdditions_$VBOX_VERSION.iso"
	config.vbguest.auto_update = true
	config.vbguest.no_remote = false
	
	config.ssh.forward_agent = true
	
	local_developer = (ENV['DOP_USERNAME']) ? ENV['DOP_USERNAME'] : "dop"

##############
# LOCAL
##############
	config.vm.define "dop-#{local_developer}" do |development_config|
		
		if local_developer.nil? then
			puts "The DOP_USERNAME environment variable must be set to a unique value within the project, i.e. your username"
			exit
		end
		
		development_config.vm.hostname = "dop-#{local_developer}"
		
		# network
		development_config.vm.network :private_network, ip: "10.0.0.1"
	
		# shared folders
		# tbd
	
		# virtualbox
		development_config.vm.box = "debian-6.0.7-amd64"
		development_config.vm.box_url = "boxes/debian-6.0.7-amd64.box"
	
		# virtualbox options
		development_config.vm.provider :virtualbox do |v|
			v.gui = false
			v.customize ["modifyvm", :id, "--memory", 2048]
			v.customize ["modifyvm", :id, "--cpus", 2]
			v.customize ["modifyvm", :id, "--cpuexecutioncap", "90"]
		end
	
		# chef solo
		development_config.vm.provision :chef_solo do |chef|
			chef.cookbooks_path = ['../chef/cookbooks']
			chef.data_bags_path = ['../chef/data_bags']
			chef.encrypted_data_bag_secret_key_path = "../chef/data_bag_key"
			chef.roles_path = "../chef/roles"
			chef.add_role("vagrant")
			chef.json.merge!(
				'dop_base' => {
					'local_developer' => local_developer
				}
			)
		end
	end
end